metadata:
  name: argocd-dev

query_params:
  upsert: true

spec:
  project: cloudops
  source:
    chart: argo-cd
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: "5.51.4"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
