metadata:
  name: keycloak-dev

query_params:
  upsert: true

spec:
  project: cloudops
  source:
    chart: keycloak
    repoURL: "https://codecentric.github.io/helm-charts"
    targetRevision: "18.4.0"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
