repositories:
  bitnami:
    method: create
    enabled: true

  ingress-nginx:
    method: create
    enabled: false
      
  prometheus-community:
    method: create
    enabled: true

  customer-repo:
    method: create
    enabled: false
    
  genesis:
    method: create
    enabled: true
    secrets:
      azure:
        vault_url: "https://oorja-dev-kv-bnk4ys.vault.azure.net/"
        secret_names: 
          - "genesis-username"
          - "genesis-password"
