upsert: true

metadata:
  name: genesis

spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  destinations:
    - server: '*'
      namespace: '*'

  sourceRepos:
    - 'https://github.com/HARMAN-DTS/Genesis'
